"""fix_enum_names

Revision ID: 254439bbd623
Revises: 0001_initial
Create Date: 2026-03-08 21:17:19.367211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254439bbd623'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_logs_action', table_name='activity_logs')
    op.drop_index('idx_logs_created', table_name='activity_logs')
    op.drop_index('idx_logs_target', table_name='activity_logs')
    op.drop_index('idx_logs_user', table_name='activity_logs')
    op.create_index(op.f('ix_activity_logs_action_type'), 'activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.drop_index('idx_alerts_active', table_name='alerts')
    op.drop_index('idx_alerts_province', table_name='alerts')
    op.create_index('idx_alerts_location', 'alerts', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_alerts_province'), 'alerts', ['province'], unique=False)
    op.drop_index('idx_zones_polygon', table_name='disaster_zones', postgresql_using='gist')
    op.drop_index('idx_zones_type', table_name='disaster_zones')
    op.create_index('idx_disaster_zones_polygon', 'disaster_zones', ['polygon'], unique=False, postgresql_using='gist')
    op.drop_index('idx_notif_created', table_name='notifications')
    op.drop_index('idx_notif_user', table_name='notifications')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index('idx_report_images_report', table_name='report_images')
    op.create_index(op.f('ix_report_images_report_id'), 'report_images', ['report_id'], unique=False)
    op.drop_index('idx_reports_created_at', table_name='reports')
    op.drop_index('idx_reports_dtype', table_name='reports')
    op.drop_index('idx_reports_province', table_name='reports')
    op.drop_index('idx_reports_status', table_name='reports')
    op.drop_index('idx_reports_submitted_by', table_name='reports')
    op.drop_index('idx_reports_title_trgm', table_name='reports', postgresql_using='gin')
    op.create_index(op.f('ix_reports_province'), 'reports', ['province'], unique=False)
    op.drop_index('idx_resources_org', table_name='resources')
    op.drop_index('idx_resources_status', table_name='resources')
    op.create_index(op.f('ix_resources_org_id'), 'resources', ['org_id'], unique=False)
    op.drop_index('idx_support_active', table_name='support_offers')
    op.drop_index('idx_support_location', table_name='support_offers', postgresql_using='gist')
    op.drop_index('idx_support_org', table_name='support_offers')
    op.create_index('idx_support_offers_location', 'support_offers', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_support_offers_org_id'), 'support_offers', ['org_id'], unique=False)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_name_trgm', table_name='users', postgresql_using='gin')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_name_trgm', 'users', ['full_name'], unique=False, postgresql_using='gin')
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_support_offers_org_id'), table_name='support_offers')
    op.drop_index('idx_support_offers_location', table_name='support_offers', postgresql_using='gist')
    op.create_index('idx_support_org', 'support_offers', ['org_id'], unique=False)
    op.create_index('idx_support_location', 'support_offers', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_support_active', 'support_offers', ['is_active'], unique=False)
    op.drop_index(op.f('ix_resources_org_id'), table_name='resources')
    op.create_index('idx_resources_status', 'resources', ['status'], unique=False)
    op.create_index('idx_resources_org', 'resources', ['org_id'], unique=False)
    op.drop_index(op.f('ix_reports_province'), table_name='reports')
    op.create_index('idx_reports_title_trgm', 'reports', ['title'], unique=False, postgresql_using='gin')
    op.create_index('idx_reports_submitted_by', 'reports', ['submitted_by'], unique=False)
    op.create_index('idx_reports_status', 'reports', ['status'], unique=False)
    op.create_index('idx_reports_province', 'reports', ['province'], unique=False)
    op.create_index('idx_reports_dtype', 'reports', ['disaster_type'], unique=False)
    op.create_index('idx_reports_created_at', 'reports', [sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_report_images_report_id'), table_name='report_images')
    op.create_index('idx_report_images_report', 'report_images', ['report_id'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.create_index('idx_notif_user', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_notif_created', 'notifications', [sa.text('created_at DESC')], unique=False)
    op.drop_index('idx_disaster_zones_polygon', table_name='disaster_zones', postgresql_using='gist')
    op.create_index('idx_zones_type', 'disaster_zones', ['zone_type'], unique=False)
    op.create_index('idx_zones_polygon', 'disaster_zones', ['polygon'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_alerts_province'), table_name='alerts')
    op.drop_index('idx_alerts_location', table_name='alerts', postgresql_using='gist')
    op.create_index('idx_alerts_province', 'alerts', ['province'], unique=False)
    op.create_index('idx_alerts_active', 'alerts', ['is_active', 'expires_at'], unique=False)
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action_type'), table_name='activity_logs')
    op.create_index('idx_logs_user', 'activity_logs', ['user_id'], unique=False)
    op.create_index('idx_logs_target', 'activity_logs', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_logs_created', 'activity_logs', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_logs_action', 'activity_logs', ['action_type'], unique=False)
    # ### end Alembic commands ###
